const { contextBridge, ipcRenderer } = require('electron')

// <browser-action-list> / <button is="browser-action"> — icône et popup des
// extensions (uBlock Origin) dans la barre d'outils.
try { require('electron-chrome-extensions/browser-action').injectBrowserAction() } catch {}

// Chargé synchronement avant que app.js tourne — élimine tout problème de timing
const __divoInitState     = ipcRenderer.sendSync('state-load-sync')
const __divoInitHistory   = ipcRenderer.sendSync('history-load-sync')
const __divoInitSessions  = ipcRenderer.sendSync('sessions-load-sync')
const __divoInitPasswords = ipcRenderer.sendSync('passwords-load-sync')

contextBridge.exposeInMainWorld('bridge', {
  minimize:             () => ipcRenderer.send('window-minimize'),
  maximize:             () => ipcRenderer.send('window-maximize'),
  close:                () => ipcRenderer.send('window-close'),
  newtabUrl:            'divo://newtab',
  settingsUrl:          'divo://settings',
  toggleFullscreen:     () => ipcRenderer.send('toggle-fullscreen'),
  focusWebview:         (id) => ipcRenderer.send('focus-webview', id),
  openFile:             (p)  => ipcRenderer.send('open-file', p),
  openDlFolder:         ()   => ipcRenderer.send('open-dl-folder'),
  answerPermission:     (key, granted) => ipcRenderer.send('answer-permission', key, granted),
  onDlStart:            (cb) => ipcRenderer.on('dl-start',          (_, d) => cb(d)),
  onDlUpdate:           (cb) => ipcRenderer.on('dl-update',         (_, d) => cb(d)),
  onDlDone:             (cb) => ipcRenderer.on('dl-done',           (_, d) => cb(d)),
  onOpenNewTab:         (cb) => ipcRenderer.on('open-new-tab',      (_, u) => cb(u)),
  onFullscreenChange:   (cb) => ipcRenderer.on('fullscreen-change', (_, v) => cb(v)),
  onPermissionRequest:  (cb) => ipcRenderer.on('permission-request',(_, d) => cb(d)),
  adblockStatus: ()        => ipcRenderer.invoke('adblock-status'),
  adblockToggle: (v)       => ipcRenderer.invoke('adblock-toggle', v),
  importChromeBookmarks: () => ipcRenderer.invoke('import-chrome-bookmarks'),
  setTheme: (theme) => ipcRenderer.invoke('set-theme', theme),
  importBookmarksHtml:   () => ipcRenderer.invoke('import-bookmarks-html'),
  getDownloadPath:    () => ipcRenderer.invoke('get-download-path'),
  pickDownloadPath:   () => ipcRenderer.invoke('pick-download-path'),
  webDarkModeStatus: () => ipcRenderer.invoke('web-dark-mode-status'),
  webDarkModeToggle: (v) => ipcRenderer.invoke('web-dark-mode-toggle', v),
  httpsUpgradeStatus: () => ipcRenderer.invoke('https-upgrade-status'),
  httpsUpgradeToggle: (v) => ipcRenderer.invoke('https-upgrade-toggle', v),
  onWebviewShortcut:    (cb) => ipcRenderer.on('webview-shortcut',  (_, d) => cb(d)),
  onUpdateAvailable:    (cb) => ipcRenderer.on('update-available',    (_, d) => cb(d)),
  onUpdateProgress:     (cb) => ipcRenderer.on('update-progress',     (_, p) => cb(p)),
  installUpdate:        ()    => ipcRenderer.invoke('install-update'),
  getUpdateStatus:      ()    => ipcRenderer.invoke('get-update-status'),
  checkUpdateNow:       ()    => ipcRenderer.invoke('check-update-now'),
  isDefaultBrowser:     ()    => ipcRenderer.invoke('is-default-browser'),
  setDefaultBrowser:    ()    => ipcRenderer.invoke('set-default-browser'),
  onNotDefaultBrowser:  (cb)  => ipcRenderer.on('not-default-browser', () => cb()),
  getUserExtensions:    ()    => ipcRenderer.invoke('get-user-extensions'),
  installExtById:       (id)  => ipcRenderer.invoke('install-extension-by-id', id),
  removeUserExtension:  (id)  => ipcRenderer.invoke('remove-user-extension', id),
  toggleUserExtension:  (id, enabled) => ipcRenderer.invoke('toggle-user-extension', id, enabled),
  onExtensionInstalled: (cb)  => ipcRenderer.on('extension-installed', (_, d) => cb(d)),
  extTabActivated:      (id)  => ipcRenderer.send('ext-tab-activated', id),
  extCreateTabResult:   (requestId, webContentsId) => ipcRenderer.send('ext-create-tab-result', { requestId, webContentsId }),
  onExtCreateTab:       (cb)  => ipcRenderer.on('ext-create-tab', (_, d) => cb(d)),
  onExtRemoveTab:       (cb)  => ipcRenderer.on('ext-remove-tab', (_, id) => cb(id)),
  onExtSelectTab:       (cb)  => ipcRenderer.on('ext-select-tab', (_, id) => cb(id)),
  initState:    __divoInitState,
  initHistory:  __divoInitHistory,
  historySave:  (h) => ipcRenderer.invoke('history-save', h),
  initSessions:   __divoInitSessions,
  sessionsSave:   (s) => ipcRenderer.invoke('sessions-save', s),
  initPasswords:  __divoInitPasswords,
  passwordsSave:  (p) => ipcRenderer.invoke('passwords-save', p),
  captureTab:          (id) => ipcRenderer.invoke('capture-tab', id),
  onNotificationClick: (cb) => ipcRenderer.on('notification-click', (_, wcId) => cb(wcId)),
  stateSave: (s)   => ipcRenderer.invoke('state-save', s),
  rendererLog: (msg) => ipcRenderer.send('renderer-log', msg),
  exportProfile:      () => ipcRenderer.invoke('profile-export'),
  importProfile:      () => ipcRenderer.invoke('profile-import'),
  getActiveProfile:   () => ipcRenderer.invoke('get-active-profile'),
  getAllProfiles:      () => ipcRenderer.invoke('get-all-profiles'),
  switchProfile:      () => ipcRenderer.invoke('switch-profile'),
  editActiveProfile:  (d) => ipcRenderer.invoke('edit-active-profile', d),
})